import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Learn anytime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Import Poppins font from Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@100;300;400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
